version: '3.8'

services:
  authentication-service:
    image: devjoseeverton/authentication-service:v1
    container_name: auth-service
    ports:
      - "8080:8080"
    restart: always
    environment:
      RABBITMQ_HOST: rabbitmq
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      RABBIT_USERNAME: ${RABBIT_USERNAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
    depends_on:
      - rabbitmq
    networks:
      - app_network

  email-service:
    image: devjoseeverton/email-service:v1
    container_name: email_service
    ports:
      - "8181:8181"
    restart: always
    environment:
      RABBITMQ_HOST: rabbitmq
      EMAIL_LOGIN: ${EMAIL_LOGIN}
      EMAIL_SENHA: ${EMAIL_SENHA}
      RABBIT_USERNAME: ${RABBIT_USERNAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
    depends_on:
      - rabbitmq
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_container
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
