spring:
  application:
    name: user-service
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
rabbitmq:
  emailpendente:
    exchange: email-pendente.ex

springdoc:
  swagger-ui:
    path: /docs-auth.html
  api-docs:
    path: /docs-auth
  packagesToScan: com.ej.authentication.web.controllers
