spring:
  application:
    name: email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_LOGIN}
    password: ${EMAIL_SENHA}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
rabbitmq:
  queue:
    email:
      pendente: email-pendente.ms-email-service
